apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-user
  namespace: dev-namespace

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dev-namespace
  name: dev-reader
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-reader-binding
  namespace: dev-namespace
subjects:
  - kind: ServiceAccount
    name: dev-user
    namespace: dev-namespace
roleRef:
  kind: Role
  name: dev-reader
  apiGroup: rbac.authorization.k8s.io

---
kubectl create token dev-user --namespace dev-namespace
=> eyJhbGciOiJSUzI1NiIsImtpZCI6Il9Rb3QzNUNuX2RhWjFDRVdQMmUtaGpraVlaNVFILVNReU0xdUtxbW1aajgifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzM3MTI3NzI3LCJpYXQiOjE3MzcxMjQxMjcsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiODZmYjEzZjctZTMzYS00MjA1LThlODQtZGJiOGViZjkxOWM4Iiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkZXYtbmFtZXNwYWNlIiwic2VydmljZWFjY291bnQiOnsibmFtZSI6ImRldi11c2VyIiwidWlkIjoiY2UwMjFlZTAtYzAxMi00MjU1LWEyYWEtODc0Y2NlOGY3NzliIn19LCJuYmYiOjE3MzcxMjQxMjcsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZXYtbmFtZXNwYWNlOmRldi11c2VyIn0.ryfMypda_TDYnWPG1Zuw9WFHPXzdBpiW1czY__L13okynsFbthAEiV2hrcc-G_qG3KM4cVN20NXbq3p07NEvASIW-5NV-voVdZP1Oj7uEzqhy8BWJCU9vsfyTUmA0by1gW83XI4cOw-yFzPZqpS5FZolP9rrNd1QOjeUJb1Z7avJrKAZTDqMaHyFG4OV7OwbBRxhk4GLw0UH2yz0LEJbOcsmVSkHjebbbVDWQBDxcdT3MwNk8f4FcBFcZh-3bL6HDQ_zd65QuhXnUNYvKCpNNqQGe8FItIxYDvQygMy7hysEPJzeuPz77EakPiCSWiro6iVyrIxP_XZHpQWEm3vbng
---
kubectl config set-credentials dev-user --token=eyJhbGciOiJSUzI1NiIsImtpZCI6Il9Rb3QzNUNuX2RhWjFDRVdQMmUtaGpraVlaNVFILVNReU0xdUtxbW1aajgifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzM3MTI3ODY4LCJpYXQiOjE3MzcxMjQyNjgsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiOGEyOTA4NzktZWI1My00M2Q2LWExYjktZTRjM2YzNzZiOWYwIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkZXYtbmFtZXNwYWNlIiwic2VydmljZWFjY291bnQiOnsibmFtZSI6ImRldi11c2VyIiwidWlkIjoiY2UwMjFlZTAtYzAxMi00MjU1LWEyYWEtODc0Y2NlOGY3NzliIn19LCJuYmYiOjE3MzcxMjQyNjgsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZXYtbmFtZXNwYWNlOmRldi11c2VyIn0.rpo3jPaHRtY-Hi39Svtacj_tKMX5iJ8_NbkPklWRUXIUNSXI8sZ13MUK4LorBuBiRqb0dKxEbnId6GcicHvBKFfsSMQzOSvH29Ckm1y4e8N0aXETq6EXsjC-A4g9YLwnzrqnKuDrhj-dcZ3Jjsx3Nd4CxsifG-2mgcAPzeXXjAURH6cTJUFNttxITUQiroYGXM9JCNlR9vWkitFjJ7Ew2Z1Hw-W1-ZOMSscDqqo1DtUCRULkwi4KSUdtv99o_DD7udstTEgWmen2Fm3gdhWM0D2uvSLKLNmPW_RTlO4rGgnZ27-4trwHC8JBiV2cqagsbx0LfNTbjQvYnoJ38ntjBQ
---
kubectl config set-context dev-user --cluster=kubernetes --user=dev-user --namespace=dev-namespace
