apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dev-namespace
  name: dev-reader
rules:
- apiGroups: ["*"] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["*"] # "" indicates the core API group
  resources: ["configmaps"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-reader-binding
  namespace: dev-namespace
subjects:
- kind: ServiceAccount
  name: dev-user # "name" is case sensitive
  namespace: dev-namespace
  apiGroup: ""
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: dev-reader # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io