
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    tier: critical  
  name: resource-pod
spec:
  containers:
  - command:
    - sleep
    - "3600"
    image: busybox:1.34
    name: resource-pod
    resources:
      requests:
        memory: "128Mi"
        cpu: "200m"
      limits:
        memory: "256Mi"
        cpu: "500m"
  nodeSelector:
    tier: critical
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}