apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: resource-pod
  name: resource-pod
spec:
  containers:
  - image: busybox:1.34
    command: ["sleep","3600"]
    name: resource-pod
    resources:
      requests:
        memory: "128Mi"
        cpu: "200m"
      limits:
        memory: "256Mi"
        cpu: "500m"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always

  nodeSelector:
    tier: critical

status: {}

---

kubectl label nodes node01 tier=critical