apiVersion: v1
kind: Pod
metadata:
  name: resource-pod
spec:
  containers:
  - name: busybox
    image: busybox:1.34
    resources:
      requests:
        memory: "128Mi"
        cpu: "200m"
      limits:
        memory: "256Mi"
        cpu: "500m"
    command: ["sleep", "3600"]
    ports:
    - containerPort: 80
  nodeSelector:
    tier: critical