
apiVersion: v1
kind: Pod
metadata:
  name: resource-pod
spec:
  containers:
  - name: resource-pod
    image: busybox:1.34 
    command: ["sh", "-c", "sleep 3600"]
    resources:
      requests:
        memory: "128Mi"
        cpu: "200m"
      limits:
        memory: "256Mi"
        cpu: "500m"
    ports:
    - containerPort: 80
  nodeSelector:
    tier: critical
