apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage
provisioner: rancher.io/local-path
reclaimPolicy: Retain
allowVolumeExpansion: false
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: storage
  hostPath:
    path: "/mnt/data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-data
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Mi
  storageClassName: storage

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-app
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.21
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: site-data
          ports:
            - containerPort: 80

      volumes:
        - name: site-data
          persistentVolumeClaim:
            claimName: pvc-data

---
apiVersion: v1
kind: Service
metadata:
  name: storage-app-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
