apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: failing-pod
  name: failing-pod
spec:
  containers:
    - image: busybox:1.34
      name: failing-pod
      command: ["sh", "-c", "echo Hello && exit 1"]
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: failing-pod
  name: failing-pod
spec:
  containers:
    - image: busybox:1.34
      name: failing-pod
      command: ["sh", "-c", "echo Hello && sleep 3600"]
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
