apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pending-pod
  name: pending-pod
spec:
  containers:
    - image: nginx:1.21
      name: pending-pod
      resources:
        limits:
          cpu: "100m"
          memory: "128Mi"
        requests:
          cpu: "100m"
          memory: "128Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
