apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pending-pod
  name: pending-pod
spec:
  containers:
  - image: nginx:1.21
    name: pending-pod

    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "100m"

    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}