apiVersion: apps/v1
kind: Deployment
metadata:
  name: broken-service-deployment
  labels:
    app: broken-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: broken-service-deployment
  template:
    metadata:
      labels:
        app: broken-service-deployment
    spec:
      containers:
      - name: broken-service-deployment
        image: nginx:1.21
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: broken-service
spec:
  selector:
    app: broken-service-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080