apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: broken-service-deployment
  name: broken-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: broken-service-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: broken-service-deployment
    spec:
      containers:
        - image: nginx:1.21
          name: nginx
          ports:
            - containerPort: 80
          resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: broken-service-deployment
  name: broken-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: broken-service-deployment
status:
  loadBalancer: {}
